app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestHelper.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/UiAutomator2Exception.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoGetter.java
app/src/main/java/io/appium/uiautomator2/core/InteractionController.java
app/src/main/java/io/appium/uiautomator2/core/QueryController.java
app/src/main/java/io/appium/uiautomator2/core/UiAutomatorBridge.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/LongPressKeyCode.java
app/src/main/java/io/appium/uiautomator2/handler/MultiPointerGesture.java
app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java
app/src/main/java/io/appium/uiautomator2/handler/Source.java
app/src/main/java/io/appium/uiautomator2/handler/TouchDown.java
app/src/main/java/io/appium/uiautomator2/handler/TouchEvent.java
app/src/main/java/io/appium/uiautomator2/handler/TouchMove.java
app/src/main/java/io/appium/uiautomator2/handler/TouchUp.java
app/src/main/java/io/appium/uiautomator2/handler/request/SafeRequestHandler.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/model/internal/NativeAndroidBySelector.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java
app/src/main/java/io/appium/uiautomator2/server/ServerInstrumentation.java
app/src/main/java/io/appium/uiautomator2/utils/Device.java
app/src/main/java/io/appium/uiautomator2/utils/ReflectionUtils.java
app/src/main/java/io/appium/uiautomator2/utils/XMLHierarchy.java
package.json

- Updated throwing RuntimeException to more appropriate exceptions.
Reason for change: Netty server explicitly catching all RuntimeExceptions and throwing it's own custom messages like **server hangup** and external modules who calls server don't have control actual exception.
- Updated UiAutomator2Exception to extend Exception from RuntimeException
- Updated [CustomUIDevice](https://github.com/sravanmedarapu/appium-uiautomator2-server/blob/code_refactor/app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java#L178).
Reason for updated: `mInstrumentation.getUiAutomation().getRootInActiveWindow()` returning `null` randomly, need to figure out actual root cause, for time being repolling for maximum 5 times for getting root node for being non null.

Code refactor

---

app/src/main/java/io/appium/uiautomator2/http/AppiumResponse.java

JSONWP proxy contains the following verification for JSON response:
```js
resBody = util.safeJsonParse(resBody);
if (_.includes(statusCodesWithRes, response.statusCode) &&
(_.isUndefined(resBody.status) || _.isUndefined(resBody.value))) {
throw new Error(`Did not get a valid response object. Object was: ${JSON.stringify(resBody)}`);
}
```
This means we get an exception even in case of correct response, since the valid _null_ value is deliberately not included there inside server code. Now this is fixed.
Addresses https://github.com/appium/appium/issues/8810

Allow null values in JSON response

---

app/src/main/java/io/appium/uiautomator2/http/AppiumResponse.java

It looks like JSONObject does not really like to contain Java _null_ values and requires JSONObject.NULL to be set instead.

Fix setting null to JSONObject's value

---

app/src/main/java/io/appium/uiautomator2/handler/UpdateSettings.java
app/src/main/java/io/appium/uiautomator2/model/WaitForIdleTimeout.java

This is to set the waitForIdleTimeout via settings, which will help user to override the default Idle timeout(10 *1000).
For example, If there are elements which only appears in the screen for less than 5 seconds. In a video player, player controls overlay disappears in 5 seconds. UIAutomator2 waits for screen to become idle and failed to identify the element since there is a default idle timeout of 10 seconds.
This resolves the issue appium/appium#9147
From clients, We can set settings like driver.setSetting(Setting.WAIT_FOR_IDLE_TIMEOUT, 0);

set waitForIdleTimeout via settings

---

app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java

`UiObject.clearTextField()` method [can not clear password text field](https://android.googlesource.com/platform/frameworks/uiautomator/+/android-support-test/src/main/java/android/support/test/uiautomator/UiObject.java#693) because `getText()` returns empty string, but we can mimic [`UiObject2.clear()`](https://android.googlesource.com/platform/frameworks/uiautomator/+/android-support-test/src/main/java/android/support/test/uiautomator/UiObject2.java#337) behaviour.
Related to appium/appium-uiautomator2-driver#109

Replace `clearTextField()` with `setText('')`

---

app/build.gradle
app/src/main/java/io/appium/uiautomator2/handler/W3CActions.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java
app/src/main/java/io/appium/uiautomator2/test/W3CActionsPreprocessingTests.java
app/src/main/java/io/appium/uiautomator2/test/W3CActionsTransformationTests.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsConstants.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsParseException.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

This PR implements extended support of [W3C Actions spec](https://github.com/jlipps/simple-wd-spec#perform-actions) with UIA2 framework. Not all of things have been tested "in the wild" yet - only the basic set touch actions.
I've also updated Gradle setup to be able to work with the source in the recent Android Studio and to execute basic integration tests directly in the IDE.
I can say the implementation has reached beta stage and can be merged, however the feedback from end users needs to be extensively monitored and potential issues should be reviewed and addressed There are two most important things there we have to pay attention to:
- Client library implementation details (this is done on Selenium side and cannot be controlled by us, at least directly)
- Actions translation to …

W3C Actions Support

---

app/src/main/java/io/appium/uiautomator2/handler/GetElementScreenshot.java

~~I've checking again with `getContext`.~~ ✅ 
---
I encountered the following error when I ran https://github.com/appium/ruby_lib_core/pull/33/files .
`InstrumentationRegistry.getInstrumentation().getContext()`'s context is for `io.appium.uiautomator2.test`.
`InstrumentationRegistry.getInstrumentation().getTargetContext()`'s context is for `io.appium.uiautomator2`.
In this case, the file should store via `io.appium.uiautomator2`.
After the change, I could save the screenshot expectedly.
```
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: java.io.IOException: Permission denied
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280) …
```

use getTargetContext to save file in allowed area for GetElementScreenshot 

---

.gitignore
.npmignore
doc/release.md
index.js
package.json
update-gradle-version.js

Publishing now becomes a matter of running the normal flow. `npm version major|minor|patch` will build the apks and put them in a place known to the index. `npm publish` will create a tarball that includes the corresponding apks for use.
Usage would become a matter of importing the package and getting the `SERVER_APK_PATH` and `TEST_APK_PATH`. E.g., in the `appium-uiautomator2-driver` package,
```js
// -import { UI2_SERVER_APK_PATH as apkPath, UI2_TEST_APK_PATH as testApkPath, UI2_VER} from './installer';
import { UI2_VER } from './installer';
import { SERVER_APK_PATH as apkPath, TEST_APK_PATH as testApkPath } from 'appium-uiautomator2-server';
```

Streamline publishing

---

app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java

The `Device.waitForIdle` in `XPathFinder.java` shouldn't use hardcoded value 10*1000 ms. It should be UiAutomator who decide whether use default timeout value or read from user's setting. 
This also related to https://github.com/appium/appium/issues/9147. When there are some continues background animation, user may try to set a small `waitForIdleTimeout` to prevent it from hanging. But if he try to search XPath, it will seem like the setting has no effect.

Shouln't use hardcoded timeout for waitForIdle().

---

app/src/main/java/io/appium/uiautomator2/handler/CaptureScreenshot.java
app/src/main/java/io/appium/uiautomator2/handler/GetElementScreenshot.java

Actually, the previous screenshoting endpoint was not working properly at all, since it was not returning Base64-encoded screenshot string. Now it's fixed. Also, I've get rid of unnecessary files creation, so the process should be much faster now.
@vmaxim Please take a look when you have time

Speed up screenshoting

---

app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java
app/src/test/java/io/appium/uiautomator2/model/settings/CompressedLayoutHierarchyTests.java

If your device is super fast and you are lucky enough, you can catch a rare exception:
```java
io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: error while invoking method android.view.accessibility.AccessibilityNodeInfo android.support.test.uiautomator.QueryController.getRootNode() on object android.support.test.uiautomator.QueryController@74ff6f1 with parameters []
at io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:93)
at io.appium.uiautomator2.core.QueryController.getAccessibilityRootNode(QueryController.java:37)
at io.appium.uiautomator2.model.XPathFinder.getRootAccessibilityNode(XPathFinder.java:238)
at io.appium.uiautomator2.model.XPathFinder.refreshUiElementTree(XPathFinder.java:224)
at …
```

Ignore `IllegalStateException` while getting root node

---

app/src/main/java/io/appium/uiautomator2/core/EventRegister.java
app/src/main/java/io/appium/uiautomator2/core/InteractionController.java
app/src/main/java/io/appium/uiautomator2/core/ReturningRunnable.java
app/src/main/java/io/appium/uiautomator2/handler/GetSessionDetails.java
app/src/main/java/io/appium/uiautomator2/handler/NewSession.java
app/src/main/java/io/appium/uiautomator2/handler/Swipe.java
app/src/main/java/io/appium/uiautomator2/model/AccessibilityScrollData.java
app/src/main/java/io/appium/uiautomator2/model/AppiumUiAutomatorDriver.java
app/src/main/java/io/appium/uiautomator2/model/Session.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

It is desirable to know certain things about scroll views / list views, for example how much content is in them in terms of pixels or child elements. Because elements don't exist until scrolled into view, this is not possible.
However, the scroll accessibility event does contain this info, so we can examine it retroactively after a scroll action.
This PR traps that data and puts it on the session object, so it can be retrieved by a call to get the session details.

expose data about last scroll

---

package.json

Move the moving of apks into the build task, so that a user can run `npm run build` while working (say, while linking the package) and have everything in working order.
Also add `npm run clean-device` to do a rudimentary clean of the apks from the device (no handling of different devices connected, etc).

Add task for cleaning device

---

app/build.gradle
app/src/main/java/io/appium/uiautomator2/handler/GetClipboard.java
app/src/main/java/io/appium/uiautomator2/handler/SetClipboard.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java
app/src/main/java/io/appium/uiautomator2/utils/ClipboardHelper.java
app/src/test/java/io/appium/uiautomator2/utils/ClipboardHelperTests.java

this add clipboard handling primitives, so one can automate copypaste operations better. Only plain text clipboard format is supported, but the implementation allows to extend this.
@vmaxim Please take a look at this when you have time.

Add system clipboard handlers

---

app/src/main/java/io/appium/uiautomator2/handler/GetClipboard.java
app/src/main/java/io/appium/uiautomator2/handler/SetClipboard.java

related: https://github.com/appium/ruby_lib_core/pull/69#issuecomment-377466959
When I ran clip feature against Andorid, I encounterd the below error. To avoid the error, I've implemented `runOnMainSync` to run clip feature on main thread.
After this PR, ruby_lib_core's tests run perfectly for clip features on Android.
```
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:209)
at android.os.Handler.<init>(Handler.java:123)
at android.content.ClipboardManager$2.<init>(ClipboardManager.java:69)
at android.content.ClipboardManager.<init>(ClipboardManager.java:69)
at android.app.SystemServiceRegistry$12.createService(SystemServiceRegistry.java:276)
at …
```

fix to run clip feature on runOnMainSync

---

app/src/main/java/io/appium/uiautomator2/handler/UpdateSettings.java
app/src/main/java/io/appium/uiautomator2/model/settings/ActionAcknowledgmentTimeout.java
app/src/main/java/io/appium/uiautomator2/model/settings/KeyInjectionDelay.java
app/src/main/java/io/appium/uiautomator2/model/settings/ScrollAcknowledgmentTimeout.java
app/src/main/java/io/appium/uiautomator2/model/settings/WaitForSelectorTimeout.java
app/src/test/java/io/appium/uiautomator2/handler/UpdateSettingsTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/ActionAcknowledgmentTimeoutTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/KeyInjectionDelayTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/ScrollAcknowledgmentTimeoutTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/WaitForSelectorTimeoutTests.java

Implement https://github.com/appium/appium-android-driver/pull/153 for uiautomator2.
`WaitForIdleTimeout` was implemented in https://github.com/appium/appium-uiautomator2-server/pull/111 and all this PR also followed the setting. I also removed unused `import`.
All tests are green 💚 `./gradlew test`

Add uiautomator configurations

---

app/src/main/java/io/appium/uiautomator2/handler/UpdateSettings.java
app/src/main/java/io/appium/uiautomator2/model/Session.java
app/src/main/java/io/appium/uiautomator2/model/settings/ElementResponseAttributes.java
app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java
app/src/test/java/io/appium/uiautomator2/handler/UpdateSettingsTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/ElementResponseAttributesTest.java

Fix https://github.com/appium/appium-uiautomator2-server/pull/128 to use same capability name as used in https://github.com/appium/WebDriverAgent/pull/69.

Rename elementResponseFields to elementResponseAttributes

---

app/src/main/java/io/appium/uiautomator2/handler/GetSettings.java
app/src/main/java/io/appium/uiautomator2/handler/UpdateSettings.java
app/src/main/java/io/appium/uiautomator2/model/settings/ActionAcknowledgmentTimeout.java
app/src/main/java/io/appium/uiautomator2/model/settings/AllowInvisibleElements.java
app/src/main/java/io/appium/uiautomator2/model/settings/CompressedLayoutHierarchy.java
app/src/main/java/io/appium/uiautomator2/model/settings/ElementResponseFields.java
app/src/main/java/io/appium/uiautomator2/model/settings/EnableNotificationListener.java
app/src/main/java/io/appium/uiautomator2/model/settings/KeyInjectionDelay.java
app/src/main/java/io/appium/uiautomator2/model/settings/ScrollAcknowledgmentTimeout.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/model/settings/ShouldUseCompactResponses.java
app/src/main/java/io/appium/uiautomator2/model/settings/WaitForIdleTimeout.java
app/src/main/java/io/appium/uiautomator2/model/settings/WaitForSelectorTimeout.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java
app/src/test/java/io/appium/uiautomator2/handler/GetSettingsTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/ActionAcknowledgmentTimeoutTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/AllowInvisibleElementsTest.java
app/src/test/java/io/appium/uiautomator2/model/settings/CompressedLayoutHierarchyTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/ElementResponseFieldsTest.java
app/src/test/java/io/appium/uiautomator2/model/settings/KeyInjectionDelayTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/ScrollAcknowledgmentTimeoutTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/ShouldUseCompactResponsesTest.java
app/src/test/java/io/appium/uiautomator2/model/settings/WaitForIdleTimeoutTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/WaitForSelectorTimeoutTests.java

After finishing this PR, we can get settings reverting https://github.com/appium/appium-uiautomator2-driver/pull/158 
```ruby
[3] pry(#<AppiumLibCoreTest::Android::DeviceTest>)> @@driver.get_settings
=> {"actionAcknowledgmentTimeout"=>3000,
"allowInvisibleElements"=>false,
"ignoreUnimportantViews"=>false,
"elementResponseAttributes"=>false,
"enableNotificationListener"=>true,
"keyInjectionDelay"=>0,
"scrollAcknowledgmentTimeout"=>200,
"shouldUseCompactResponses"=>true,
"waitForIdleTimeout"=>10000,
"waitForSelectorTimeout"=>10000}
[4] pry(#<AppiumLibCoreTest::Android::DeviceTest>)> @@driver.update_settings('ignoreUnimportantViews' => true)
=> true
[5] pry(#<AppiumLibCoreTest::Android::DeviceTest>)> @@driver.get_settings
=> {"actionAcknowledgmentTimeout"=>3000, …
```

add get settings

---

.travis.yml
app/build.gradle
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/Config.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/BaseTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/Client.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/RootRequired.java
app/src/androidTestServer/java/io/appium/uiautomator2/server/test/AppiumUiAutomator2Server.java
app/src/main/AndroidManifest.xml
app/src/main/java/io/appium/uiautomator2/handler/DeleteSession.java
app/src/main/java/io/appium/uiautomator2/handler/UpdateSettings.java
app/src/main/java/io/appium/uiautomator2/model/settings/AbstractSetting.java
app/src/main/java/io/appium/uiautomator2/model/settings/CompressedLayoutHierarchy.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/model/settings/ShutdownOnPowerDisconnect.java
app/src/main/java/io/appium/uiautomator2/server/ServerInstrumentation.java
app/src/test/java/io/appium/uiautomator2/handler/UpdateSettingsTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/CompressedLayoutHierarchyTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/ShutdownOnPowerDisconnectTest.java
app/src/test/java/io/appium/uiautomator2/server/ServerInstrumentationTests.java

Shutdown the server through the broadcast receiver on [ACTION_POWER_DISCONNECTED](https://developer.android.com/reference/android/content/Intent.html#ACTION_POWER_DISCONNECTED). 
This behaviour can be controlled using `shutdownOnPowerDisconnect` setting whose value is `true` by default.
Addressed to: appium/appium#9412
CI results: https://travis-ci.org/vmaxim/appium-uiautomator2-server/builds/371962846

Shutdown server on ACTION_POWER_DISCONNECT

---

app/src/main/java/io/appium/uiautomator2/handler/GetBatteryInfo.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java
app/src/main/java/io/appium/uiautomator2/utils/BatteryHelper.java

just because this was requested

Add an endpoint for getting battery information

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ActionsCommandsTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/commands/DeviceCommands.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/commands/ElementCommands.java
app/src/main/java/io/appium/uiautomator2/handler/LongPressKeyCode.java
app/src/main/java/io/appium/uiautomator2/handler/PressKeyCode.java
app/src/main/java/io/appium/uiautomator2/handler/W3CActions.java
app/src/main/java/io/appium/uiautomator2/utils/InteractionUtils.java
app/src/main/java/io/appium/uiautomator2/utils/JSONUtils.java

The actual idea has been borrowed from the Espresso's implementation of `performEditorAction` method.

Add a possibility to emulate IME actions with press_keycode endpoint

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ActionsCommandsTest.java
app/src/main/java/io/appium/uiautomator2/handler/W3CActions.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/W3CKeyCode.java
app/src/test/java/io/appium/uiautomator2/utils/w3c/W3CActionsTransformationTests.java

The current implementation properly uses Unicode POA representation of pressable keys

Make W3C keys input more compatible to the standard

---

app/src/main/java/io/appium/uiautomator2/core/UiAutomation.java
app/src/main/java/io/appium/uiautomator2/model/NotificationListener.java
app/src/test/java/io/appium/uiautomator2/model/NotificationListenerTests.java

```UiAutomation.mOnAccessibilityEventListener``` is no longer accessible on Android P
```
W tomator2.serve: Accessing hidden field Landroid/app/UiAutomation;->mOnAccessibilityEventListener:Landroid/app/UiAutomation$OnAccessibilityEventListener; (blacklist, reflection)
```
https://android-developers.googleblog.com/2018/02/improving-stability-by-reducing-usage.html

Fix appium/appium#10707

---

app/src/main/java/io/appium/uiautomator2/utils/XMLHierarchy.java

I investigated https://github.com/appium/appium/issues/9934 further and finally, I found the cause.
The error was:
```
Original error: org.w3c.dom.DOMException: android.support.v7.app.ActionBar.ˋ
at org.apache.harmony.xml.dom.NodeImpl.setNameNS(NodeImpl.java:241)
at org.apache.harmony.xml.dom.DocumentImpl.renameNode(DocumentImpl.java:318)
at io.appium.uiautomator2.utils.XMLHierarchy.visitNode(XMLHierarchy.java:122)
at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:88)
at io.appium.uiautomator2.utils.XMLHierarchy.annotateNodes(XMLHierarchy.java:89)
...
```
The `ˋ` was the cause and it was `\xCB\x8B`. `\u0060`(\x60) is <code>`</code> from keyboard.
After the change, parsing `class="android.support.v7.app.ActionBar$ˋ"`worked.

fix parsing \xCB\x8B

---

.npmignore
package.json

Small win in tarball size, but on-disk size is pretty significant:
```
npm notice === Tarball Details ===
npm notice name:          appium-uiautomator2-server
npm notice version:       1.16.0
npm notice filename:      appium-uiautomator2-server-1.16.0.tgz
npm notice package size:  4.9 MB
npm notice unpacked size: 10.5 MB
npm notice shasum:        734ed66b9220ebac87ccbf522730f3b323c0485a
npm notice integrity:     sha512-sIkcuB0VV98NG[...]++cqSjvtDoR+g==
npm notice total files:   29
npm notice
appium-uiautomator2-server-1.16.0.tgz
```
```
npm notice === Tarball Details ===
npm notice name:          appium-uiautomator2-server
npm notice version:       1.16.0
npm notice filename:      appium-uiautomator2-server-1.16.0.tgz
npm notice package size:  3.5 MB
npm notice unpacked size: 3.5 MB
npm …
```

Do not include gradle files in npm package

---

package.json
scripts/sign-apk.js

* Does this on 'build' so that we publish an APK that contains the Appium certificate
* This is so that the server doesn't have to run 'apksigner' during a session

Sign apk with default appium certificate

---

app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java

We're running Appium tests in a react-native app and when trying to update RN to version 59 it started reporting React Native's TextInput as `android.view.View` in the accessibility layer. The problem is that `nodeInfo.getClassName()` returns `null` for this class. I don't know if it's normal, but I can see this with non-appium uiautomator2 test as well. The tests will crash with NPE if `isToastElement` is called on `android.view.View` element.
Stack trace:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
at io.appium.uiautomator2.model.UiObject2Element.isToastElement(UiO …

Fix NPE in UIObject2Element.isToastElement when the class name is null

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/ReflectionUtils.java

This removes the redundant uiElementIndex attribute from page source output. This attribute is only used to assist xpath search and is not needed to be shown.

Remove the redundant uiElementIndex attribute from the source tree

---

app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/model/KnownElements.java
app/src/main/java/io/appium/uiautomator2/utils/ElementLocationHelpers.java

The accessibility is refreshed anyway when xml page source is built

Avoid refreshing accessibility twice while executing xpath queries

---

app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/Source.java
app/src/main/java/io/appium/uiautomator2/model/KnownElements.java

after more extensive testing it looks like getting the page source itself does not refresh the tree, so it is necessary to call the corresponding method on our own.

Add AX tree refresh before getting the page source

---

app/src/main/java/io/appium/uiautomator2/utils/XMLHelpers.java

Android XML DOM parser does not understand Unicode characters in node names (due to https://issuetracker.google.com/issues/37008591), so we must replace these with underscores

Rewrite node names to make them compatible with Android XML parser

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/commands/GestureCommands.java
app/src/main/java/io/appium/uiautomator2/handler/Flick.java

**Reasons:**
1. JsonWireProtocol supports JSON Parameters `xspeed` & `yspeed` as https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtouchflick-1
2. Appium-base-driver uses `xspeed` & `yspeed` too as https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L280
3. It can compatible when we use automatioName `Appium` or `UiAutomator2`

Update options for /touch/flick endpoint

---

app/src/main/java/io/appium/uiautomator2/utils/Logger.java

the logging level is INFO by default, and can be overridden with setprop or
/data/local.prop file (changing the latter requires rebooting the device)
for details see
https://developer.android.com/reference/android/util/Log#isLoggable(java.lang.String,%20int)
fixes #241

make logging configurable

---

app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java

There is no need to rebuild the UI hierarchy for XML creation, since it is always gets rebuilt before on findElement(s)/source call (inside `refreshRootAXNode`)

Speed up xpath and source commands

---

app/src/main/java/io/appium/uiautomator2/handler/GetSessionDetails.java
app/src/main/java/io/appium/uiautomator2/handler/NewSession.java
app/src/main/java/io/appium/uiautomator2/model/AppiumUiAutomatorDriver.java
app/src/main/java/io/appium/uiautomator2/model/Session.java

Addresses https://github.com/appium/appium/issues/12162
@jlipps There are several other places where getSession is called like this without checking for nullability. I'd better leave it to you to perform the necessary fixes, since the code has to do with AccessibilityScrollData stuff.

Avoid NPE on getting session details

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/commands/DeviceCommands.java
app/src/main/AndroidManifest.xml
app/src/main/java/io/appium/uiautomator2/handler/GetDeviceInfo.java
app/src/main/java/io/appium/uiautomator2/utils/DeviceInfoHelper.java

Addresses https://github.com/appium/appium/issues/12502

Add detailed network info to the device information endpoint

---

app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/utils/Device.java

Each `find` called ended up calling `Device.waitForIdle` three times, which is not necessary. Also make use of the `waitForIdleTimeout`.
This has been tested with the `appium-uiautomator2-driver` as well (https://travis-ci.org/appium/appium-uiautomator2-driver/builds/539680318).

Only wait for idle once on find

---

app/src/main/java/io/appium/uiautomator2/core/InteractionController.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/model/settings/TrackScrollEvents.java

Add `trackScrollEvents ` cap, to configure the tracking of scroll movement. This improves performance of touch actions significantly:
Using a simple touch action:
```js
const action = new wd.TouchAction();
action.press({x: 100, y: 100})
.wait(100)
.release();
await driver.performTouchAction(action);
```
- `trackScrollEvents ` set to `true`, averages 1710ms
- `trackScrollEvents` set to `false`, averages 194ms
This could be changed to a setting if it is found to be necessary to switch between configurations mid-session.

Make scroll tracking configurable with a cap

---

app/src/main/java/io/appium/uiautomator2/core/EventRegister.java

I had copy-and-pasted this block for usage of `session.getCapability()` but as @mykola-mokhnach pointed out, it's totally unnecessary. This is the only place where this sort of thing is done.

Remove unneeded try/catch

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoHelpers.java

Described in [Appium #12892](https://github.com/appium/appium/issues/12892)

Added limit to avoid stackoverflows when calculating visible bounds

---

app/src/main/java/io/appium/uiautomator2/model/settings/AllowInvisibleElements.java
app/src/main/java/io/appium/uiautomator2/model/settings/ElementResponseAttributes.java
app/src/main/java/io/appium/uiautomator2/model/settings/ShouldUseCompactResponses.java

It does not make much sense to keep these settings from being changed in runtime

Make some caps configurable in runtime

---

app/src/main/java/io/appium/uiautomator2/handler/Clear.java
app/src/main/java/io/appium/uiautomator2/handler/Click.java
app/src/main/java/io/appium/uiautomator2/handler/Drag.java
app/src/main/java/io/appium/uiautomator2/handler/Status.java
app/src/main/java/io/appium/uiautomator2/model/settings/AcquireWakeLock.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/model/settings/WakeLockTimeout.java
app/src/main/java/io/appium/uiautomator2/server/ServerInstrumentation.java

Addresses https://github.com/appium/appium/issues/13111

feat: Add server setting which allows to control the global wake lock

---

app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

Let me update grade and test library's versions
This should not break anything.
----
note:
From targetSdkVersion 29, `NetworkInfo` was marked as deprecated. So, we should update them before Android 11.
https://github.com/appium/appium-uiautomator2-server/compare/master...KazuCocoa:update-for-api-level29?expand=1

feat: update gradle version and test libraries

---

app/src/main/java/io/appium/uiautomator2/handler/GetDeviceInfo.java
app/src/main/java/io/appium/uiautomator2/utils/DeviceInfoHelper.java

Fixes https://github.com/appium/appium-uiautomator2-server/issues/314

fix: Avoid using the native nameForState call for BluetoothAdapter class

---

app/src/main/java/io/appium/uiautomator2/common/exceptions/CompressScreenshotException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/TakeScreenshotException.java
app/src/main/java/io/appium/uiautomator2/http/AppiumResponse.java
app/src/main/java/io/appium/uiautomator2/utils/ScreenshotHelper.java

There is no need to log the whole response value (especially if it is some long base64-encoded image)

fix: Limit the maximum size of logged responses

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ActionsCommandsTest.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsTokenizer.java
ci-jobs/ci.yml

Azure build is _very_ flakey with respect to a single test. The two errors are of the same sort, and seem to be related to timing in the typing of the capital letter:
```
10:20:57 V/InstrumentationResultParser: 1) verifyTypingText(io.appium.uiautomator2.unittest.test.ActionsCommandsTest)
10:20:57 V/InstrumentationResultParser: java.lang.AssertionError:
10:20:57 V/InstrumentationResultParser: Expected: "Hi"
10:20:57 V/InstrumentationResultParser: but: was "HHi"
```
```
09:34:11 V/InstrumentationResultParser: 1) verifyTypingText(io.appium.uiautomator2.unittest.test.ActionsCommandsTest)
09:34:11 V/InstrumentationResultParser: java.lang.AssertionError:
09:34:11 V/InstrumentationResultParser: Expected: "Hi"
09:34:11 V/InstrumentationResultParser: but: was "HHHi"
```

build: do not capitalize in typing test so azure build will pass

---

app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java

Related to https://github.com/appium/appium/issues/13886

chore: Be smarter about setting the text

---

app/src/main/java/io/appium/uiautomator2/utils/UiExpressionParser.java
app/src/main/java/io/appium/uiautomator2/utils/UiScrollableParser.java
app/src/test/java/io/appium/uiautomator2/utils/UiScrollableParserTests.java

https://github.com/appium/appium/issues/4733

fix: Avoid throwing exceptions for UiObject selectors containing methods like scrollToEnd

---

app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsConstants.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsExecutor.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsTokenizer.java
app/src/test/java/io/appium/uiautomator2/utils/w3c/W3CActionsTokenizationTests.java

I did some performance tests and it looks like the motion events generation delay of 5 ms (the same as UIAutomator framework uses) it too little for the most of devices. As the result the actual action execution period is longer than the action duration, especially on emulators. This PR increases the default value to 20ms, which improves the performance and reduces intercall delays.

fix: Increase cross events delay to improve gestures performance

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/androidTestServer/java/io/appium/uiautomator2/server/test/AppiumUiAutomator2Server.java
app/src/main/java/io/appium/uiautomator2/model/settings/MjpegBilinearFiltering.java
app/src/main/java/io/appium/uiautomator2/model/settings/MjpegFiltering.java
app/src/main/java/io/appium/uiautomator2/model/settings/MjpegScalingFactor.java
app/src/main/java/io/appium/uiautomator2/model/settings/MjpegServerFramerate.java
app/src/main/java/io/appium/uiautomator2/model/settings/MjpegServerPort.java
app/src/main/java/io/appium/uiautomator2/model/settings/MjpegServerScreenshotQuality.java
app/src/main/java/io/appium/uiautomator2/model/settings/ServerPort.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/server/ServerConfig.java
app/src/main/java/io/appium/uiautomator2/server/ServerInstrumentation.java
app/src/main/java/io/appium/uiautomator2/server/mjpeg/MjpegScreenshotClient.java
app/src/main/java/io/appium/uiautomator2/server/mjpeg/MjpegScreenshotServer.java
app/src/main/java/io/appium/uiautomator2/server/mjpeg/MjpegScreenshotStream.java
app/src/main/java/io/appium/uiautomator2/utils/ScreenshotHelper.java
app/src/test/java/io/appium/uiautomator2/handler/UpdateSettingsTests.java

While working on a project spanning both _Android_ and _iOS_ automation my team noticed that that there was `mjpeg` streaming support for _iOS_ but not _Android_. We built this internally and wanted to give it back to the open-source community.
This change-set adds mjpeg [screen] steaming support for _Android_, with reasonable defaults, configurable via the environment.
---
(Special thanks to @lc-applause for building this out, he made my job, prepping this for PR, easy)

feat: Add mjpeg [screen] streaming

---

app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java

For an UiObject element (e.g. Seekbar) the text value returned is not correct.
The page source contains the correct value but for a request of type getText,
the value is different.

Fix getText bug for UiObject element

---

app/src/main/java/io/appium/uiautomator2/model/settings/AbstractSetting.java
app/src/test/java/io/appium/uiautomator2/model/settings/AbstractSettingTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/ActionAcknowledgmentTimeoutTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/KeyInjectionDelayTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/ScrollAcknowledgmentTimeoutTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/WaitForIdleTimeoutTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/WaitForSelectorTimeoutTests.java

While adding support for _mjpeg-streaming_ some new `AbstractSetting(s)` were introduced that are / were `Integer` values (the first of their type).
While testing the integration it turns out that the values are being interpreted as `Double(s)` and as a result a `ClassCastException` is raised.
This change-set follows the pattern established for `Long` in the `convertValue` function and adds compatibility for `Integer` value(s) + related tests.

Fix `ClassCastException` for `Integer` settings values

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/model/CustomUiSelector.java
app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/model/UiElement.java
app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

When page source is built for the whole elements hierarchy that a fake `hierarchy` root is added, which contains some additional info about the display. It is also used as a holder for toast elements. Although, it makes no sense to add the same stuff to context searches where the xml root is some subelement.
https://github.com/appium/appium/issues/14509

fix: Do not add fake root for searches with context

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoHelpers.java
app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java

There's some mess happening to the `text` property before it is passed to `setText`, so it makes sense to call setProgress before all these checks and make the necessary adjustments

refactor: Tune the way progress values are set on Android API 24+

---

app/build.gradle
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/model/CustomUiSelector.java
app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
build.gradle

Unfortunately UiAutomator does not tell us anything about accessibility tree changes between findElement invokations. That is why caching of snapshots could cause the unconsistent behaviour described in https://github.com/appium/appium/issues/14586. This PR eliminates snapshots caching, so now we are going to refresh the tree for each element being snapshotted.

fix: Discard caching for element snapshots

---

app/src/main/java/io/appium/uiautomator2/common/exceptions/UnknownCommandException.java
app/src/main/java/io/appium/uiautomator2/http/AppiumResponse.java
app/src/main/java/io/appium/uiautomator2/http/HttpServer.java
app/src/main/java/io/appium/uiautomator2/http/IHttpRequest.java
app/src/main/java/io/appium/uiautomator2/http/IHttpResponse.java
app/src/main/java/io/appium/uiautomator2/http/IHttpServlet.java
app/src/main/java/io/appium/uiautomator2/http/KeepAliveStateHandler.java
app/src/main/java/io/appium/uiautomator2/http/ServerHandler.java
app/src/main/java/io/appium/uiautomator2/http/ServerInitializer.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

https://github.com/appium/appium/issues/14614

fix: Return proper response in case of missing route

---

app/src/main/java/io/appium/uiautomator2/http/AppiumResponse.java

It makes it easier to debug issues looking at logcat output

chore: Do not abbreviate stack traces in logs

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/model/NotificationListener.java
app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
app/src/main/java/io/appium/uiautomator2/utils/ElementLocationHelpers.java

Previously we were only excluding redundant attributes from the xml itself, which did not affect the performance much, but now we also exclude them from snapshots. And it does the job

fix: Properly exclude attributes from snapshots to speed up xpath lookup

---

app/src/main/java/io/appium/uiautomator2/model/Session.java
app/src/main/java/io/appium/uiautomator2/model/settings/AbstractSetting.java
app/src/main/java/io/appium/uiautomator2/model/settings/ISetting.java

Capabilities map accepts any values (type Object), but settings require strict value types

chore: Apply capabilities validation on session init

---

app/src/main/java/io/appium/uiautomator2/model/ElementsCache.java

It looks like calling `equals` on UiObject is pretty expensive, since it tries to find the connected accessibility element. Related to https://github.com/appium/appium-uiautomator2-server/issues/405

fix: Improve caching performance

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/core/AxNodeInfoHelper.java
app/src/main/java/io/appium/uiautomator2/core/InteractionController.java
app/src/main/java/io/appium/uiautomator2/handler/GetOrientation.java
app/src/main/java/io/appium/uiautomator2/handler/SetOrientation.java
app/src/main/java/io/appium/uiautomator2/handler/UpdateSettings.java
app/src/main/java/io/appium/uiautomator2/model/BaseElement.java
app/src/main/java/io/appium/uiautomator2/model/ScreenRotation.java
app/src/main/java/io/appium/uiautomator2/model/Session.java
app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
app/src/main/java/io/appium/uiautomator2/model/settings/AllowInvisibleElements.java
app/src/main/java/io/appium/uiautomator2/model/settings/ElementResponseAttributes.java
app/src/main/java/io/appium/uiautomator2/model/settings/EnableMultiWindows.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/model/settings/ShouldUseCompactResponses.java
app/src/main/java/io/appium/uiautomator2/model/settings/UseResourcesForOrientationDetection.java
app/src/main/java/io/appium/uiautomator2/server/ServerInstrumentation.java
app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/Device.java
app/src/test/java/io/appium/uiautomator2/handler/UpdateSettingsTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/AllowInvisibleElementsTest.java
app/src/test/java/io/appium/uiautomator2/model/settings/ElementResponseAttributesTest.java
app/src/test/java/io/appium/uiautomator2/model/settings/ShouldUseCompactResponsesTest.java

There is currently a mess there, since some settings are stored in caps and some other are stored in their own classes. This PR unifies that approach, so that each setting is not stored separately. Also, the way these settings are retrieved has been simplified.

refactor: Do not store settings in session capabilities

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
app/src/main/java/io/appium/uiautomator2/utils/ElementLocationHelpers.java

https://github.com/appium/appium/issues/15179

fix: Fix xpath lookup for queries including attribute matching patterns (@*)

---

app/src/main/java/io/appium/uiautomator2/core/AxNodeInfoHelper.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/FirstVisibleView.java
app/src/main/java/io/appium/uiautomator2/model/AccessibleUiObject.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/ElementsCache.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/utils/ByUiAutomatorFinder.java
app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java

the idea behind this PR is that each located element is backed up by a particular AccessibilityNodeInfo instance with `mSourceNodeId` and `mWindowId` properties, which define the uniqueness of each element. So, instead of assigning random UUID to each newly located element we are trying to be smart instead and calculate the cache identifier value based on the actual property values. This guarantees that equal accessibility elements would have equal cache identifiers.

refactor: Unify element cache identifiers

---

app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

Per the _WebDriver_ protocol spec, get active element should be a `GET` not a `POST` (https://www.w3.org/TR/webdriver/#dfn-get-active-element). This change-set corrects a recently merged change.
As a future task we will submit a PR to deprecate the `POST` version of `/active` if it still exists on _XCUITest_ and add the `GET` variant.

fix: Active element should be a GET not a POST

---

app/src/main/java/io/appium/uiautomator2/core/AxNodeInfoExtractor.java
app/src/main/java/io/appium/uiautomator2/handler/FirstVisibleView.java
app/src/main/java/io/appium/uiautomator2/model/AccessibleUiObject.java

The `getAccessibilityNodeInfo` method of UiObject2 contains calls for `getDevice().waitForIdle()` and `mCachedNode.refresh()`, which are redundant for the case when we want to extract the cached node from a just created UiObject2 instance (and also may affect performance in some cases).

chore: skip idle checks while retrieving cached node from uiobject2

---

app/src/main/java/io/appium/uiautomator2/model/BaseElement.java
app/src/main/java/io/appium/uiautomator2/utils/PositionHelper.java
app/src/test/java/io/appium/uiautomator2/utils/PositionHelperTests.java

The PR has the same idea as https://github.com/appium/appium-uiautomator2-server/pull/435
Basically, we are not trying to outsmart anyone and let a user provide whatever coordinates they want to without throwing any exceptions. If then the resulting action works, - everything is fine, and if not, - 🤷

fix: Do not throw an exception if point coordinates are outside of the calculated screen bounds

---

app/build.gradle
app/src/main/java/io/appium/uiautomator2/model/settings/DisableIdLocatorAutocompletion.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/utils/ElementLocationHelpers.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

In general Android OS requires resource ids to be prefixed by package identifiers, so they are guaranteed to be unique. Some app frameworks don't follow this rule though. This new `disableIdLocatorAutocompletion` setting makes usage of id locators possible with apps built using these faulty frameworks. By default its value is `false`, which resembles the legacy behavior.

feat: Add a setting to disable id locators autocompletion

---

app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/server/mjpeg/MjpegScreenshotStream.java
app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/ScreenshotHelper.java

Related to https://github.com/appium/appium-uiautomator2-server/issues/462
As a part of https://github.com/appium/appium-uiautomator2-server/pull/289 appium started supporting [FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES](https://developer.android.com/reference/android/app/UiAutomation#FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES)
In order to do so the Configurator instance is initialised here 
https://github.com/appium/appium-uiautomator2-server/blob/d3cd4a3baa4209d02afcdd2fc0007717890bf138/app/src/main/java/io/appium/uiautomator2/server/ServerInstrumentation.java#L69-L70
While this configurator comes into affect whenever uiautomation instance is used from UiAutomatorBridge
https://github.com/appium/appium-uiautomator2-server/blob/700eefebb75f8c7e2d3d1feac3b6d0d13e8b339d/app/src/main/java/io/a …

fix: Pass Uiautomator flags to all instances

---

app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsTokenizer.java

- To enable long press functionality without any
preset timeouts, it is now possible to trigger PointerDown
in one ActionChain, do stuff in between and release the
button using PointerUp in other ActionChain.
- Example usage with python:
from appium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
ActionChains(driver1).click_and_hold(ptt_button).perform()
print ("Free to do stuff here!!")
ActionChains(driver1).release(ptt_button).perform()

Remove restriction of PointerDown before PointerUp

---

app/src/main/AndroidManifest.xml

Afaik, this external storage permission existed from the beginning. Espresso driver does not have this, so potentially can uia2 server also remove this...? This may needed something old devices such as SD card required one to save data...?
I tested with this change in ruby_lib_core's test cases locally, including push/pull files and screenshot stuff, but no error occurred related to this permission.
(This is not https://github.com/appium/appium/issues/17679 's fix. I just thought this permission's necessity)
updated:
Perhaps.... push to SD card storage area may require this...? <- push/pull is basically via adb, so maybe not needed for the permission
> In particular, if your app targets Android 11 (API level 30) or higher, the WRITE_EXTERNAL_STORAGE permission doesn't have any effect on …

chore: remove android.permission.WRITE_EXTERNAL_STORAGE

---

app/src/main/java/io/appium/uiautomator2/handler/ActiveElement.java

hi team, thank you for taking a look.
Recently I faced an issue where Active Element command results in 404 error and found that issue has gone after I added PageSource command before invoking Active Element command. After reading the code, I found that can be caused by a stale accessibility cache.
In my case, I don't use FindElement(s) but Action command (pointerMove + pointerDown + pointerUp) to select the element. Looks like there is no chance to refresh the cache in such a case and ActiveElement cannot find a focused element if node information has been changed by that tap action.
Does it make sense to refresh the accessibility cache when finding the active element?

chore: refresh accessibility cache before searching active element

---

app/src/main/java/io/appium/uiautomator2/model/settings/EnableTopmostWindowFromActivePackage.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java

This Pull Request presents a feature that enables the retrieval of a non-focusable window from the same package, positioned at a layer above the active window. Similar to #301.
This enhancement offers an additional advantage (especially when using XPath locators) in E2E tests. Unlike the `enableMultiWindows` setting, this new feature negates the need to consider the number of windows displayed at any given time, thereby improving test portability.
- Implementation of a new strategy to identify and retrieve the topmost window among all windows corresponds to the active package.
- Addition of `enableTopmostWindowFromActivePackage` settings API to toggle this feature.
- By default, the feature is disabled, ensuring that existing functionalities remain unaffected unless the user explicitly …

feat: settings API to get the topmost window from active package

---

app/src/main/java/io/appium/uiautomator2/core/AxNodeInfoHelper.java
app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/model/settings/SnapshotMaxDepth.java

Add `snapshotMaxDepth` setting API to be able to detect deep depth elements. Added this parameter as setting API as same as [appium-xcuitest-driver](https://appium.github.io/appium-xcuitest-driver/4.32.5/settings/)
issue https://github.com/appium/appium-uiautomator2-server/issues/516

feat: add snapshotMaxDepth to be able to detect deep depth elements

---

.github/workflows/functional-test.yml
app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsTokenizer.java

We do not want to calculate coordinates for a very first pointerMove action in the chain as it is there to simply define the initial position of the cursor
Related to https://github.com/appium/java-client/issues/1954

fix: Ignore start coordinates for the very first move action

---

app/src/main/java/io/appium/uiautomator2/http/ServerHandler.java

This PR aims to enhance compatibility with previous appium versions by removing the "/wd/hub" prefix from URIs.
I am currently using Appium version 1.22.3, and I faced compatibility issues with the latest version of UIAutomator2 regarding the URI. I discovered that requests with the prefix "/wd/hub" were not compatible. By implementing a change to remove this specific prefix from incoming requests, I was able to enhance compatibility, allowing the latest version of UIAutomator2 to work with previous versions of Appium as well. This solution ensures a more seamless integration between these different versions, bridging the gap that existed due to the URI inconsistency.

chore: remove "/wd/hub" prefix to improve compatibility

---

.github/workflows/unit-test.yml

to avoid the latest npm's nodejs version mismatch error

ci: remove npm update

---

app/src/main/java/io/appium/uiautomator2/core/AxNodeInfoHelper.java

https://github.com/appium/appium-uiautomator2-server/issues/534

fix: Possible race condition NPE

---

app/build.gradle

It looks like this include was only supposed to be used in e2e tests but I don't observe any real invocation of it. Perhaps, it's some leftover from the past...

chore: Remove espresso from dependencies list

---

app/build.gradle
app/src/main/AndroidManifest.xml

Lets try to use newer `targetSdkVersion`
AS has helpful feature to show suggestions we should fix in the upgrade. According to the hint, we should:
Bluetooth is the manifest update.
The 2nd one is https://developer.android.com/topic/performance/app-hibernation :
> If your app targets Android 11 (API level 30) or higher, and the user doesn't [interact with your app](https://developer.android.com/topic/performance/app-hibernation#app-usage) for a few months, the system places your app in a hibernation state. The system optimizes for storage space instead of performance, and the system protects user data. This system behavior is similar to what occurs when the user manually force-stops your app from system settings.
so maybe not related to the uia2 server.
The 3rd one is may not for the …

feat: bump targetSdkVersion from 30 to 31, and to 32

---

app/src/main/java/io/appium/uiautomator2/core/UiAutomatorBridge.java

https://github.com/appium/appium-uiautomator2-server/issues/490#issuecomment-1870480657
Tested on Android 14 by calling `mobile:deviceInfo`:
Before
> {"androidId"=>"6d1ee9298ac43e90", "apiVersion"=>"34", "bluetooth"=>{"state"=>"ON"}, "brand"=>"google", "carrierName"=>"", "displayDensity"=>420, "locale"=>"en_US", "manufacturer"=>"Google", "model"=>"Pixel 7", "networks"=>[{"capabilities"=>{"SSID"=>nil, "linkDownBandwidthKbps"=>55349, "linkUpstreamBandwidthKbps"=>12000, "networkCapabilities"=>"NET_CAPABILITY_NOT_METERED,NET_CAPABILITY_INTERNET,NET_CAPABILITY_NOT_RESTRICTED,NET_CAPABILITY_TRUSTED,NET_CAPABILITY_NOT_VPN,NET_CAPABILITY_VALIDATED,NET_CAPABILITY_NOT_ROAMING,NET_CAPABILITY_FOREGROUND,NET_CAPABILITY_NOT_CONGESTED,NET_CAPABILITY_NOT_SUSPENDED", "signalStrength"=>-41, …

feat: get default display via displaymanager

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java

[Update]:
Below one has been resolved by calling `Build.VERSION_CODES.TIRAMISU` condition with `accessibilityService.clearCache();` While existing method works with Android 14, probably the recommended way will be safe.
[Original]
One concern is https://developer.android.com/about/versions/13/changes/non-sdk-13#new-blocked
> The following code box lists all of the non-SDK interfaces that were unsupported in Android 12 (API level 31) that are blocked in Android 13 (API level 33). That is, these interfaces belong to the max-target-s list, so your app can only use these interfaces if it targets Android 12 (API level 31) or lower.
> Our goal is to make sure that public alternatives are available before we restrict non-SDK interfaces, and we understand that your app might have a valid use case …

feat: bump targetSdkVersion to 33

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

https://github.com/appium/appium-uiautomator2-server/blob/855b71fc90aeb456c8dc8edf5868f51c2c6f4a45/app/build.gradle#L8 already sets the gradle version as 8.2.0, thus this is kind of to fit all gradle version to the existing latest one

chore: use gradle 8.2.0

---

app/src/main/java/io/appium/uiautomator2/core/UiAutomatorBridge.java

A future compatibility fix in https://github.com/appium/appium-uiautomator2-server/issues/490
It looks like androidx.test.uiautomator.UiDevice in 2.3.0-beta01 dropped `getDefaultDisplay`, thus all versions should follow the `displayManager.getDisplay(Display.DEFAULT_DISPLAY);` way. The current master has no issue with the 2.2.0 version.
The API itself has existed since API level 17 https://developer.android.com/reference/android/hardware/display/DisplayManager#getDisplay(int), thus this change should be safe. (I have tested with an Android 9 real device. It worked)
I have tested `displayManager.getDisplay(Display.DEFAULT_DISPLAY);` works with Android 9 as well.

fix: use displayManager.getDisplay only for upcoming androidx.test.uiautomator:uiautomator:2.3.0-beta01

---

app/src/main/java/io/appium/uiautomator2/model/BySelectorHelper.java
app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/model/internal/Gestures.java
app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java

Done in preparation to UIA lib update to the version 2.3.0, where passing of `null` selector to UiObject2 is not allowed in the constructor.

refactor: Tune the logic of BySelector creation

---

app/build.gradle
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ActionsCommandsTest.java
app/src/main/java/io/appium/uiautomator2/core/AxNodeInfoHelper.java
app/src/main/java/io/appium/uiautomator2/handler/gestures/Drag.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/model/internal/GestureController.java
app/src/main/java/io/appium/uiautomator2/model/internal/Gestures.java
app/src/main/java/io/appium/uiautomator2/model/internal/PointerGesture.java
app/src/main/java/io/appium/uiautomator2/utils/gestures/Click.java
app/src/main/java/io/appium/uiautomator2/utils/gestures/DoubleClick.java
app/src/main/java/io/appium/uiautomator2/utils/gestures/LongClick.java

Technically it is not a breaking change, although I expect some things might be broken because of the bump and significant changes in the dependent lib. So it would be safer to bump the major version and carefully check the integration with the driver first.

feat!: Bump androidx.test.uiautomator:uiautomator version to 2.3.0-beta01

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java

On my local device testing, it looks like this PR change would improve the stability of the scrollByUiSelectorTest.
The purpose of the testing is `UiSelector` with `scrollToElement`. Current master's scenario does not do any scroll as the screen size in the fact. This will let the scenario conduct actual scroll

test: improve stability of scrollByUiSelectorTest

---

app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java

This should not change anything, but this change will let `accessibilityNodeInfo` keep non-null in both cases consistently.
The `obtain` is available since API level 14.

chore: get AccessibilityNodeInfo via obtain for lower version

---

app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java

Presumably fixes https://github.com/appium/appium-uiautomator2-server/issues/596

fix: Revert the clearCache change for API 33+

---

.github/workflows/functional-test.yml
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ActionsCommandsTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/AlertCommandsTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/Config.java

It looks like some failure occurred in the middle of `setupDragDropView`, so before running actual test

test: open activity directly and add ignore to reduce flaky tests on CI env

---

app/src/main/java/io/appium/uiautomator2/utils/ScreenshotHelper.java

Addresses https://github.com/appium/appium-uiautomator2-server/issues/608
I turns out the `Bitmap.createBitmap` does not always create a new Bitmap instance and may also return the same instance that has been passed in arguments.

fix: Recycling of screenshot bitmaps

---

app/src/main/java/io/appium/uiautomator2/core/InteractionController.java
app/src/main/java/io/appium/uiautomator2/core/UiAutomatorBridge.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/utils/ContentSizeHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsExecutor.java

These helpers are not used anymore since jwp touch actions have been removed.

chore: Remove unused helpers

---

app/src/main/java/io/appium/uiautomator2/utils/XMLHelpers.java
app/src/test/java/io/appium/uiautomator2/utils/XMLHelpersTests.java

Related to https://discuss.appium.io/t/unicodedecodeerror-raised-by-driver-page-source/43843

fix: Always make sure we put valid utf8-encoded strings into attribute values

---

app/src/main/java/io/appium/uiautomator2/utils/XMLHelpers.java
app/src/test/java/io/appium/uiautomator2/utils/XMLHelpersTests.java

Reverts appium/appium-uiautomator2-server#661
It turned out there was a [bug in Node.js](https://github.com/appium/appium/issues/20503#issuecomment-2357928628) causing encoding issues. This server patch may reverted now as obsolete

fix: Revert "fix: Always make sure we put valid utf8-encoded strings into attribute values"

---

.github/workflows/functional-test.yml
.github/workflows/publish.js.yml
.github/workflows/unit-test.yml
app/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

Plus https://github.com/appium/appium-uiautomator2-server/pull/664

feat: bump gradle version

---

app/build.gradle
app/src/main/java/io/appium/uiautomator2/server/mjpeg/MjpegScreenshotClient.java
app/src/test/java/io/appium/uiautomator2/server/MjpegScreenshotTest.java

There was an issue with the Client implementation: if a socket started a connection on the internal MJPEG port and was never initialized, the entire server thread would be stuck in the while loop waiting for the client to send something.
This broke other clients connected to the server: no frames would be received anymore.
To reproduce on emulator / real device:
- Start an Appium server with mJPEG server enabled (`appium:mjpegServerPort:9100` for instance)
- Start an Appium session that reads the mJPEG frames (using Appium Inspector for instance)
- Then from `adb shell`: connect to the internal mJPEG server (default port 7810): `nc localhost 7810`
- --> Streaming will be broken for the existing clients
- Another way to reproduce instead of using the phone shell would be from the host …

fix: stuck MJPEG clients when one client fails to initialize

---

.github/workflows/unit-test.yml
app/src/test/java/io/appium/uiautomator2/server/MjpegScreenshotTest.java

I realized a bit too late that the tests I added in https://github.com/appium/appium-uiautomator2-server/pull/676 were flaky when  re-running the entire test suite:
` ./gradlew testServerDebugUnitTest   --rerun-tasks`
One of the tests would randomly (roughly 50% of the runs) fail with:
```
MjpegScreenshotTest > shouldNotBlockOnUnInitializedClient FAILED
java.lang.AssertionError: expected:<200> but was:<-1>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotTest.shouldNotBlockOnUnInitializedClient(MjpegScreenshotTest.java:101)
```
I realized I was not sending a proper HTTP response, just some raw …

test: fix unit test flakiness on MjpegScreenshotTest

---

app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
app/src/main/java/io/appium/uiautomator2/utils/Attribute.java

We previously worked on a similar PR that added more fields to the UI elements here:
https://github.com/appium/appium-uiautomator2-server/pull/682
Now, I’d like to add a few additional fields:
- `tooltip-text` - The value of AccessibilityNodeInfo::getTooltipText() - In many cases, this data can be obtained from the `content-desc` field, but for some apps a separate field is necessary (particularly for Flutter and React Native apps);
- `text-has-clickable-span` - A new custom field that describes whether there are ClickableSpan or URLSpan elements in the TextView content. We need to check if the TextView has clickable elements and thus actually can be focused.
Both fields are empty for most elements and will appear only on specific nodes, so there will be no page source bloat.

 feat: add tooltip-text and text-has-clickable-span attributes to UI elements

---

app/src/main/java/io/appium/uiautomator2/core/UiAutomation.java
app/src/main/java/io/appium/uiautomator2/core/UiAutomatorBridge.java

The previous approach may raise unexpected `java.lang.SecurityException: Calling from not trusted UID!` exceptions

fix: Use getTargetContext to fetch the display service
