appium/appium-uiautomator2-server

README.md
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/ScrollTo.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

Test Cases for Scroll, Swipe, Longclick Handlers

Test Cases for Scroll, Swipe, Longclick Handlers

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/InvalidCoordinatesException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/InvalidSelectorException.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/handler/AppStrings.java
app/src/main/java/io/appium/uiautomator2/handler/Drag.java
app/src/main/java/io/appium/uiautomator2/handler/Location.java
app/src/main/java/io/appium/uiautomator2/handler/RotateScreen.java
app/src/main/java/io/appium/uiautomator2/handler/ScrollTo.java
app/src/main/java/io/appium/uiautomator2/handler/Swipe.java
app/src/main/java/io/appium/uiautomator2/handler/TouchLongClick.java
app/src/main/java/io/appium/uiautomator2/handler/WaitForIdle.java
app/src/main/java/io/appium/uiautomator2/handler/Wake.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java
app/src/main/java/io/appium/uiautomator2/utils/PositionHelper.java

Code refactored and added Javadoc

Code refactored and added Javadoc

---

app/src/main/java/io/appium/uiautomator2/handler/Source.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java
app/src/main/java/io/appium/uiautomator2/utils/ReflectionUtils.java

New handler: **Source**
**JSON Wire Protocol end point :** [/session/:sessionId/source](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidsource)
Need to add the corresponding handlers test in UIAutomator2 driver module.

Added Source handler

---

app/src/main/java/io/appium/uiautomator2/handler/Location.java

Updated import statements to use `org.json` package

updated Location handler

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/handler/MultiPointerGesture.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

- Implemented MultiPointerGesture handler by taking [android-bootstrap](https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/handler/MultiPointerGesture.java) as a referance
- Added unit test for MultiPointerGesture

Added MultiPointerGesture and corresponding test

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/handler/GetScreenOrientation.java
app/src/main/java/io/appium/uiautomator2/handler/RotateScreen.java
app/src/main/java/io/appium/uiautomator2/model/OrientationEnum.java
package.json

Updated screen orientation handler and corresponding tests

Updated orientation handler and corresponding tests

---

app/src/main/java/io/appium/uiautomator2/handler/TouchDown.java
app/src/main/java/io/appium/uiautomator2/handler/TouchEvent.java
app/src/main/java/io/appium/uiautomator2/handler/TouchMove.java
app/src/main/java/io/appium/uiautomator2/handler/TouchUp.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

Added Touch up,Touch move and Touch down handlers.

Added Touch up,Touch move and Touch down handlers

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestHelper.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/UiSelectorSyntaxException.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoGetter.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/PressBack.java
app/src/main/java/io/appium/uiautomator2/handler/ScrollTo.java
app/src/main/java/io/appium/uiautomator2/handler/Wake.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/By.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/model/internal/AndroidElementsHash.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/model/internal/NativeAndroidBySelector.java
app/src/main/java/io/appium/uiautomator2/utils/Device.java
app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/UiAutomatorParser.java
app/src/main/java/io/appium/uiautomator2/utils/UiScrollableParser.java
app/src/main/java/io/appium/uiautomator2/utils/UiSelectorParser.java
package.json

- Implemented by taking the reference from [android-bootstrap](https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/AndroidElementsHash.java#L131) module
- As findElement using "-android uiautomator" returns [UiObject](https://github.com/sravanmedarapu/appium-uiautomator2-server/blob/findBy_uiautomator/app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java#L102) instance instead of [UiObject2 ](https://github.com/sravanmedarapu/appium-uiautomator2-server/blob/findBy_uiautomator/app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java#L84), Updated AndroidElement [class ](https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/model/AndroidElement.jav …

Find by "-android uiautomator" implementation and corresponding tests 

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/handler/Swipe.java

Modified Swipe handler  according to the json from the driver. Driver changes [here](https://github.com/appium/appium-uiautomator2-driver/pull/25)

Modified Swipe handler and integrated with driver module

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestHelper.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/handler/Clear.java
app/src/main/java/io/appium/uiautomator2/handler/Click.java
app/src/main/java/io/appium/uiautomator2/handler/CompressedLayoutHierarchy.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/Flick.java
app/src/main/java/io/appium/uiautomator2/handler/RotateScreen.java
app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java
app/src/main/java/io/appium/uiautomator2/handler/TouchEvent.java
app/src/main/java/io/appium/uiautomator2/handler/TouchLongClick.java
app/src/main/java/io/appium/uiautomator2/http/AppiumResponse.java
app/src/main/java/io/appium/uiautomator2/http/HttpServer.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java
app/src/main/java/io/appium/uiautomator2/server/ServerInstrumentation.java
app/src/main/java/io/appium/uiautomator2/utils/XMLHierarchy.java
package.json

-  Updated json body for FindElement/FindElements and element based actions like (click, clear, flick, e.t.c) to be in sync with driver module

Code refactor

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/handler/request/SafeRequestHandler.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

- Added throwing StaleObjectException
- Refactored Tests

Added thowing StaleObjectException

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestHelper.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

- For all non '0' status codes returning 500 HTTP status
- Added corresponding test

500 HTTP status for unsuccessful requests

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/handler/Click.java
app/src/main/java/io/appium/uiautomator2/handler/Drag.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/By.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/model/internal/NativeAndroidBySelector.java
package.json

- Refactored Click handler to support tapping based on `x` & `y` coordinates & Added corresponding Test for `tap`
- Added `accessibility Id` support for FindElement and refactored Tests
- Removed By.name support as it is deprecated and unnecessary legacy code
- Refactored Drag and added test for drag
- Added ncp package in dependencies

Refactored Click, Drag and Added accessibility strategy to FindElement

---

.npmignore
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/androidTestServer/java/io/appium/uiautomator2/server/test/AppiumUiAutomator2Server.java
app/src/main/AndroidManifest.xml
app/src/main/java/io/appium/uiautomator2/common/exceptions/SessionRemovedException.java
app/src/main/java/io/appium/uiautomator2/handler/Click.java
app/src/main/java/io/appium/uiautomator2/handler/DeleteSession.java
app/src/main/java/io/appium/uiautomator2/handler/TouchEvent.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java
app/src/main/java/io/appium/uiautomator2/server/ServerInstrumentation.java
gradle.properties

- Added Tap Endpoint
- Added Test for TouchEvents
- Refactored Tests & DeleteSession handler
- Updated .npmignore to ignore local.properties file

Added tap end point and updated .npmignore

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/ElementNotFoundException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/UiAutomator2Exception.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoGetter.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/NewSession.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/By.java
app/src/main/java/io/appium/uiautomator2/model/CustomUiSelector.java
app/src/main/java/io/appium/uiautomator2/model/Finder.java
app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/model/UiElement.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/utils/Attribute.java
app/src/main/java/io/appium/uiautomator2/utils/NodeInfoList.java
app/src/main/java/io/appium/uiautomator2/utils/Preconditions.java
app/src/main/java/io/appium/uiautomator2/utils/XMLHierarchy.java

- Re-implemented FindElement with XPATH.

XPATH implmentation - referance droiddriver

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java

- Disabled finding element on multi window based AccessibilityWindowInfo

Disabled mutli-window and added test

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java

https://github.com/appium/appium-uiautomator2-server/issues/34

Added hierarchy as a root in the element tree for xpath finding

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestHelper.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/AndroidManifest.xml
app/src/main/java/io/appium/uiautomator2/core/UiAutomatorBridge.java
app/src/main/java/io/appium/uiautomator2/handler/DeleteSession.java
app/src/main/java/io/appium/uiautomator2/handler/Drag.java
app/src/main/java/io/appium/uiautomator2/handler/Flick.java
app/src/main/java/io/appium/uiautomator2/handler/RotateScreen.java
app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java
app/src/main/java/io/appium/uiautomator2/handler/Swipe.java
app/src/main/java/io/appium/uiautomator2/handler/TouchLongClick.java
app/src/main/java/io/appium/uiautomator2/model/NotificationListener.java
app/src/main/java/io/appium/uiautomator2/model/Session.java
app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/utils/Device.java

- Added Toast message verification support. #https://github.com/appium/appium/issues/4824
1.  Usage example with xpath `//*[@text='Clicked popup menu item Add']`
1.  It is only possible to find the element, we can't perform any operation on TOAST element. Performing any actions on TOAST element will always throw `StaleObjectException`.
- Refactored `LongTouch` json body.
- Code cleanup - avoid creating new `UiDevice` instances.

Added TOAST message verification support

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java

Find element by xpath with index attribute now.

add index attribute on buildDomNode method

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java

- FIX: Updated XPATHFinder to include special characters https://github.com/appium/appium/issues/7524
- Refactored tests.
cc: @jlipps, @imurchie

Clasname with special characters issue

---

app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java

Issue #https://github.com/appium/java-client/issues/571

Ignore elements which are not visible on the screen

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/handler/TouchEvent.java
app/src/main/java/io/appium/uiautomator2/handler/TouchLongClick.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java

Issue #https://github.com/appium/appium/issues/7621
cc: @jlipps, @imurchie

Refactored LongClick to consider duration param

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestHelper.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/TestUtil.java
app/src/main/java/io/appium/uiautomator2/handler/Click.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/ScrollTo.java
app/src/main/java/io/appium/uiautomator2/handler/WaitForIdle.java
app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/utils/Device.java

Issue #https://github.com/appium/appium/issues/8130
cc: @imurchie , @jlipps

Added waitForIdle utility method

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/HandlersTest.java
app/src/main/java/io/appium/uiautomator2/handler/GetElementAttribute.java

Fixes https://github.com/appium/appium/issues/8321

The returned value for boolean argument types should be of type string

---

app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java

fix the issue which can not get isPassword attr from UiObject or UiObject2

fix the issue(https://github.com/appium/appium/issues/6281)

---

app/src/main/java/io/appium/uiautomator2/handler/GetRect.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

As per https://github.com/appium/appium/issues/9386

Add support for get element rect endpoint

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java

As per https://github.com/appium/appium/issues/9524

Show the current value of a progress bar as text attribute

---

app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java

Related to appium/appium#8279, appium/appium#9312

Truncate text to maxLength in setText() method for API<24

---

app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java

Also removed some redundant code

Only call Clear if the corresponding field is not empty

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/utils/XMLHierarchy.java

Addresses https://github.com/appium/appium/issues/9686

Escape unsafe characters in class name

---

app/build.gradle
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoHelper.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java

This PR is based on https://github.com/appium/appium-uiautomator2-server/pull/91 by @vmaxim plus some minor improvements.

Implement a possibility to change progress bar value via setText call

---

app/src/main/java/io/appium/uiautomator2/utils/XMLHierarchy.java

Set android class to 'android.view.View' when undefined

---

app/src/main/java/io/appium/uiautomator2/handler/GetElementScreenshot.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

The PR Implements W3C endpoint `/wd/hub/session/:sessionId/element/:id/screenshot`

Add a possibility to take element screenshots

---

app/src/main/java/io/appium/uiautomator2/utils/XMLHierarchy.java

Addresses https://github.com/appium/appium/issues/9934

Extend the range of unacceptable characters for tag names 

---

app/src/main/java/io/appium/uiautomator2/handler/GetElementAttribute.java

instanceof check was incorrectly done on wrapped uiobject

fix bug in getting content size

---

app/src/main/java/io/appium/uiautomator2/handler/LongPressKeyCode.java

Addresses https://github.com/appium/appium/issues/10622
The fix is based on https://android.googlesource.com/platform/frameworks/base.git/+/9d83b4783c33f1fafc43f367503e129e5a5047fa%5E%21/#F0

Fix long press event generation

---

app/build.gradle
app/src/main/java/io/appium/uiautomator2/common/exceptions/CompressScreenshotException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/CropScreenshotException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/ElementNotFoundException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/ElementNotVisibleException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/InvalidCoordinatesException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/InvalidSelectorException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/NoAttributeFoundException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/NoSuchContextException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/PairCreationException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/SessionRemovedException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/StaleElementReferenceException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/TakeScreenshotException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/UiSelectorSyntaxException.java
app/src/main/java/io/appium/uiautomator2/common/exceptions/UnsupportedSettingException.java
app/src/main/java/io/appium/uiautomator2/handler/Clear.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java
app/src/main/java/io/appium/uiautomator2/model/KnownElements.java
app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java

I've noticed that the current implementation is very messy with implicit dependencies and conditions across the code. This refactoring tries to isolate such problems and improve the general readability.

Refactor XPathFinder class

---

.travis.yml

* Add compilation commands for Server and ServerAndroidTest.
* Fix hierarchy log output.

Tune travis compilation proccess.

---

.travis.yml
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ActionsCommandsTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/commands/DeviceCommands.java
app/src/main/java/io/appium/uiautomator2/handler/W3CActions.java

Add E2E test for W3C actions

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ActionsCommandsTest.java
app/src/main/java/io/appium/uiautomator2/handler/W3CActions.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ASCIICharacters.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ASCIICodeToKeyEventConstantTranslator.java
app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsHelpers.java
app/src/test/java/io/appium/uiautomator2/utils/w3c/W3CActionsTransformationTests.java

Add E2E tests to W3C text input actions

---

.travis.yml
app/build.gradle
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ElementCommandsTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/BaseTest.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoGetter.java
app/src/main/java/io/appium/uiautomator2/core/EventRegister.java
app/src/main/java/io/appium/uiautomator2/core/UiAutomation.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/GetRotation.java
app/src/main/java/io/appium/uiautomator2/handler/MultiPointerGesture.java
app/src/main/java/io/appium/uiautomator2/handler/WifiHandler.java
app/src/main/java/io/appium/uiautomator2/model/NotificationListener.java
app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java
app/src/main/java/io/appium/uiautomator2/model/settings/EnableNotificationListener.java
app/src/test/java/io/appium/uiautomator2/model/NotificationListenerTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/EnableNotificationListenerTests.java
app/src/test/java/io/appium/uiautomator2/server/ServerInstrumentationTests.java
build.gradle
update-gradle-version.js

Reimplement notifications listener through `UiAutomation.OnAccessibilityEventListener`.
Current implementation is slightly flaky and sometimes toast messages could not be catched even on real device. Also```onAccessibilityEventListener``` eliminates the events sync problems like a appium/appium#9328.

Listening for toasts via `OnAccessibilityEventListener`

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java

Addresses https://github.com/appium/appium/issues/10204
I've set the maximum depth to 70. Should be enough for the most of the cases, I think %)

Limit the depth of xml dump

---

app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java

Addresses https://discuss.appium.io/t/original-error-org-w3c-dom-domexception-o/22357

Avoid question marks in class names

---

app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsHelpers.java

Previously it was printing the whole action JSON instead of the particular failing action item
Addresses https://github.com/appium/appium/issues/11111

Fix exceptions output

---

app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

Addresses https://github.com/appium/appium/issues/11147

Add JSONWP alias for element screenshot endpoint

---

app/src/main/java/io/appium/uiautomator2/handler/GetDeviceInfo.java
app/src/main/java/io/appium/uiautomator2/utils/DeviceInfoHelper.java
app/src/main/java/io/appium/uiautomator2/utils/JSONUtils.java

Some users were requesting to have these values available in their automated tests

Add carrier name and real display size to device info

---

app/src/main/java/io/appium/uiautomator2/handler/GetDeviceInfo.java
app/src/main/java/io/appium/uiautomator2/utils/DeviceInfoHelper.java

This will allow to speed up driver startup by getting the necessary information directly from the server instead of performing slow adb calls

Add platform version and display density to /info endpoint

---

app/src/main/java/io/appium/uiautomator2/utils/UiExpressionParser.java

Fixes https://github.com/appium/appium/issues/11443

Allow double in uiautomator parsing

---

lib/scripts/sign-apk.js
package.json
scripts/sign-apk.js

* Transpile script instead of using babel-node

APK presign fix

---

app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java

Addresses https://github.com/appium/appium/issues/11513

Fix NPE when class name equals null

---

app/src/main/java/io/appium/uiautomator2/handler/GetElementAttribute.java
app/src/main/java/io/appium/uiautomator2/http/AppiumResponse.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/utils/Attribute.java
app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/JSONUtils.java

this makes attributes lookup case insensitive and also simplifies the downstream logic

Refactor element attributes retrieval

---

app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java

Addresses https://github.com/appium/appium/issues/11513#issuecomment-429995307

Address another NPE when class name equals to null

---

app/src/main/java/io/appium/uiautomator2/handler/W3CActions.java

Addresses https://github.com/appium/appium/issues/11536
Also, the debug logging has been improved

 Simplify up/down actions balance calculation for W3C actions

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/TestUtils.java

Separate out the multiple tests within `findElementWithContextId` and `toastVerificationTest` so when something fails it can be pinpointed.
The toast tests will still fail because https://github.com/appium/appium-uiautomator2-server/commit/919d382161acde4852ff3b34e54ebd188e460811 broke them.

Update tests for more visibility

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoHelpers.java
app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java
app/src/main/java/io/appium/uiautomator2/model/CustomUiSelector.java
app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/model/UiElement.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/utils/Attribute.java
app/src/main/java/io/appium/uiautomator2/utils/ClipboardHelper.java
app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/ReflectionUtils.java
app/src/main/java/io/appium/uiautomator2/utils/StringHelpers.java
app/src/test/java/io/appium/uiautomator2/handler/GetSettingsTests.java
app/src/test/java/io/appium/uiautomator2/model/NotificationListenerTests.java
app/src/test/java/io/appium/uiautomator2/model/settings/EnableNotificationListenerTests.java
app/src/test/java/io/appium/uiautomator2/utils/PositionHelperTests.java
app/src/test/java/io/appium/uiautomator2/utils/UiAutomatorParserTests.java

The PR does the same as https://github.com/appium/appium-uiautomator2-server/pull/212 plus a bit more

Update getText to return an empty value instead of null and bounds/displayed calculation

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/handler/Source.java
app/src/main/java/io/appium/uiautomator2/model/XPathFinder.java
app/src/main/java/io/appium/uiautomator2/utils/XMLHelpers.java
app/src/test/java/io/appium/uiautomator2/utils/XMLHelpersTests.java

I observe that DOM parser, which is built in into Android is kind'a non-maintained and contains old and annoying bugs. The StAX implementation by XMLPull looks better from this perspective, but might potentially break backwards compatibility. My proposal would be to merge this PR after 1.10 is released and give it some time for stabilization.

Switch to StAX (XMLPull) implementation for xml source building

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java

Fixes https://travis-ci.org/appium/appium-uiautomator2-driver/jobs/470125795

Tune multiple elements lookup by xpath

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java

We already have another log for xml generation perf measurement.

Measure xpath lookup perf properly

---

app/build.gradle
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/main/java/io/appium/uiautomator2/utils/ScreenshotHelper.java
build.gradle

Hopefully addresses https://github.com/appium/appium/issues/12199
Please do not merge unless the fix is confirmed as working by the problem reporter

Add a workaround for screenshot taking method

---

app/build.gradle
app/src/main/java/io/appium/uiautomator2/server/ServerInstrumentation.java
build.gradle

Simply fixed the issues that the linter was complaining about

Bump Gradle version and update wake lock tag

---

app/src/main/java/io/appium/uiautomator2/utils/ScreenshotHelper.java

Related to https://github.com/appium/appium/issues/12470
@kamza-tricentis FYI

Use UIAutomator screenshoter as a fallback

---

app/build.gradle
app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/utils/Logger.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

Addresses https://github.com/appium/appium/issues/12545

Avoid stack overlow exception by limiting the maximum recursion depth

---

app/build.gradle
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ActionsCommandsTest.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/FirstVisibleView.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/KnownElements.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/utils/Device.java
app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java
build.gradle

Addresses https://github.com/appium/appium-uiautomator2-server/issues/280

Fix cache restoration for elements with context

---

app/src/main/java/io/appium/uiautomator2/handler/GetDeviceInfo.java
app/src/main/java/io/appium/uiautomator2/utils/DeviceInfoHelper.java

https://github.com/appium/appium-xcuitest-driver/pull/1003 for UIA2
For Espresso driver is https://github.com/appium/appium-espresso-driver/pull/465

return timezone and locale as deviceInfo

---

README.md

Our runner has been moved to androix

fix package name in readme [skip ci]

---

app/src/main/java/io/appium/uiautomator2/http/HttpServer.java
app/src/main/java/io/appium/uiautomator2/http/ServerHandler.java

This should improve REST API connections performance between Appium the UIA2 server

feat: Tune SO_KEEPALIVE and TCP_NODELAY options on the server instance

---

app/src/main/java/io/appium/uiautomator2/utils/AlertHelpers.java

Related to https://github.com/appium/appium/issues/13842

fix: Update the logic for permission alert buttons selection

---

app/src/main/java/io/appium/uiautomator2/handler/SendKeysToElement.java

Addresses https://github.com/appium/appium/issues/13886

fix: Avoid calling Clear handler inside SendKeysToElement

---

package.json

closes https://github.com/appium/appium-uiautomator2-server/issues/331

chore(package): update android-apidemos to version 3.2.0

---

app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/Tap.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/Point.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/model/api/TapModel.java
app/src/main/java/io/appium/uiautomator2/utils/PositionHelper.java

Related to https://github.com/appium/appium/issues/10581

fix: Make tap handler to support both absolute and relative coordinates

---

app/src/main/java/io/appium/uiautomator2/handler/GetClipboard.java
app/src/main/java/io/appium/uiautomator2/handler/SetClipboard.java
app/src/main/java/io/appium/uiautomator2/model/api/GetClipboardModel.java
app/src/main/java/io/appium/uiautomator2/model/api/SetClipboardModel.java

Addresses https://dev.azure.com/srinivasansekar/java-client/_build/results?buildId=457&view=logs&j=dcf5f1f5-2eb6-5586-dc7f-e40285fb9e33&t=001cc609-8f94-5735-fd9e-04c1a9cbbffb

fix: Update the model for GetClipboard handler

---

app/src/main/java/io/appium/uiautomator2/http/HttpServer.java
app/src/main/java/io/appium/uiautomator2/http/KeepAliveStateHandler.java
app/src/main/java/io/appium/uiautomator2/http/ServerHandler.java
app/src/main/java/io/appium/uiautomator2/http/ServerInitializer.java

https://github.com/appium/appium/issues/14416

fix: Limit the maximum keep-alive timeout for a single channel

---

app/build.gradle
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/utils/ElementLocationHelpers.java
build.gradle

https://github.com/appium/appium-uiautomator2-server/issues/358#issuecomment-643531422

feat: Only include the actually queried attributes into the source xml

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoHelpers.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/UiAutomationElement.java
app/src/main/java/io/appium/uiautomator2/model/UiElement.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/model/settings/AbstractSetting.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/model/settings/SimpleBoundsCalculation.java

Related to https://github.com/appium/appium-uiautomator2-server/issues/358#issuecomment-652515990

feat: Unify bounds calculation and make it configurable

---

app/src/main/java/io/appium/uiautomator2/utils/Device.java

Related to https://github.com/appium/appium-uiautomator2-server/issues/365#issuecomment-656276522

chore: Skip waitForIdle call if the timeout is zero or a negative value

---

app/src/main/java/io/appium/uiautomator2/handler/BaseTouchAction.java
app/src/main/java/io/appium/uiautomator2/handler/TouchLongClick.java
app/src/main/java/io/appium/uiautomator2/model/api/touch/appium/TouchEventParams.java

https://github.com/appium/appium/issues/14601

fix: Allow to pass double values as touch event arguments

---

app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoHelpers.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/model/internal/GestureController.java
app/src/main/java/io/appium/uiautomator2/utils/ReflectionUtils.java

https://github.com/appium/appium-uiautomator2-server/issues/377

chore: Prefer native click implementation by UiObject2

---

app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java

https://github.com/appium/appium/issues/14750

fix: Add validation of UiObject existence

---

app/src/main/java/io/appium/uiautomator2/handler/NewSession.java
app/src/main/java/io/appium/uiautomator2/model/Session.java
app/src/main/java/io/appium/uiautomator2/utils/ElementLocationHelpers.java

Related to https://github.com/appium/appium/issues/15013

fix: Properly set session capabilities

---

app/src/main/java/io/appium/uiautomator2/common/exceptions/UiSelectorSyntaxException.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/model/ElementsCache.java
app/src/main/java/io/appium/uiautomator2/utils/ByUiAutomatorFinder.java
app/src/main/java/io/appium/uiautomator2/utils/ElementHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/ElementLocationHelpers.java

Related to https://github.com/appium/appium-uiautomator2-server/pull/410

refactor: Update ByUiAutomator lookup approach

---

app/src/main/java/io/appium/uiautomator2/handler/GetDevicePixelRatio.java
app/src/main/java/io/appium/uiautomator2/handler/GetSystemBars.java

Could also resolve https://github.com/appium/appium/issues/15154

chore: Simplify retrieval of system metrics

---

app/src/main/java/io/appium/uiautomator2/handler/ActiveElement.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

Add support to retrieve active element from android application.
Corresponding PR
https://github.com/appium/appium-uiautomator2-driver/pull/457
Sample response :
```
{
"value": {
"element-6066-11e4-a52e-4f735466cecf": "00000000-0000-0009-ffff-ffff0000003c",
"ELEMENT": "00000000-0000-0009-ffff-ffff0000003c"
},
"sessionId": "8cfba1e8-117e-4a34-a4c2-a4846b3010cb",
"status": 0
}
```

feat: Add active element support

---

app/src/main/java/io/appium/uiautomator2/handler/GetSessions.java

https://webdriver.io/docs/api/jsonwp/#getsessions
> getSessions
> Returns a list of the currently active sessions. Each session will be returned as a list of JSON objects containing `id` and `capabilities.`

chore: Align getSessions response with the spec

---

app/src/main/java/io/appium/uiautomator2/utils/ReflectionUtils.java

Addresses https://github.com/appium/appium/issues/15604

fix: Do not wrap runtime exceptions caused by reflected method invocation

---

app/src/main/java/io/appium/uiautomator2/core/AxNodeInfoHelper.java
app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java

Addresses https://github.com/appium/appium/issues/15708

fix: Avoid throwing an exception if range bounds are corrupted

---

app/src/main/java/io/appium/uiautomator2/core/AxNodeInfoExtractor.java
app/src/main/java/io/appium/uiautomator2/handler/FindElement.java
app/src/main/java/io/appium/uiautomator2/handler/FindElements.java
app/src/main/java/io/appium/uiautomator2/handler/FirstVisibleView.java
app/src/main/java/io/appium/uiautomator2/model/AccessibleUiObject.java
app/src/main/java/io/appium/uiautomator2/model/AndroidElement.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/utils/ByUiAutomatorFinder.java
app/src/main/java/io/appium/uiautomator2/utils/ElementLocationHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/StringHelpers.java
app/src/main/java/io/appium/uiautomator2/utils/UiAutomatorParser.java
app/src/main/java/io/appium/uiautomator2/utils/UiExpressionParser.java
app/src/main/java/io/appium/uiautomator2/utils/UiScrollableParser.java
app/src/main/java/io/appium/uiautomator2/utils/UiSelectorParser.java
app/src/test/java/io/appium/uiautomator2/utils/UiScrollableParserTests.java

Also fixes https://github.com/appium/appium/issues/15829

refactor: Tuning multiple elements lookup

---

app/build.gradle
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/test/java/io/appium/uiautomator2/model/SerializationTests.java
app/src/test/java/io/appium/uiautomator2/utils/UiSelectorParserTests.java
build.gradle

The query support is based on [Psychopath](https://wiki.eclipse.org/PsychoPathXPathProcessor/UserManual) Eclipse lib.

feat: Add support of XPath 2.0 queries

---

app/src/main/java/io/appium/uiautomator2/handler/GetDisplayDensity.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

https://github.com/appium/appium/issues/15929

feat: Add a handler to retrieve display density

---

app/build.gradle
app/src/test/java/io/appium/uiautomator2/utils/XMLHelpersTests.java

Addresses https://github.com/appium/appium/issues/16337

fix: Add missing dependency

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/Client.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/WebDriverSession.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/internal/commands/DeviceCommands.java
app/src/main/java/io/appium/uiautomator2/server/AppiumServlet.java

According to W3C spec webdriver url must not start with `/wd/hub` prefix

refactor!: Update the base url

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/main/java/io/appium/uiautomator2/core/AccessibilityNodeInfoDumper.java
app/src/main/java/io/appium/uiautomator2/model/settings/LimitXpathContextScope.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java

The PR reassembles the idea from https://github.com/appium/appium-uiautomator2-server/pull/458

feat: Add a possibility to access parent elements in context-based searches

---

app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/utils/Attribute.java

not tested yet. Will do later.
https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#getHintText() is available since api 26.
https://github.com/appium/appium/discussions/16484

feat: add hint attribute for API Level 26+

---

.github/workflows/publish.js.yml
.releaserc
package.json

ci: add release task

---

app/src/main/java/io/appium/uiautomator2/model/BaseElement.java
app/src/main/java/io/appium/uiautomator2/model/UiElementSnapshot.java
app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java
app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
app/src/main/java/io/appium/uiautomator2/model/settings/IncludeExtrasInPageSource.java
app/src/main/java/io/appium/uiautomator2/model/settings/Settings.java
app/src/main/java/io/appium/uiautomator2/utils/Attribute.java
app/src/test/java/io/appium/uiautomator2/handler/UpdateSettingsTests.java

https://github.com/appium/appium/issues/15138#issuecomment-1023633596 so, maybe we can expose `extras` in XPath as well.
I found chrome had the below extras:
```
<android.widget.FrameLayout index="1" package="com.android.chrome" class="android.widget.FrameLayout" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,83][1080,2132]" displayed="true" extras="">
<android.webkit.WebView index="0" package="com.android.chrome" class="android.webkit.WebView" text="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" long-clickable="false" password="false" scrollable="true" selected="false" …
```

feat: add extras and includeExtrasInPageSource settings

---

app/build.gradle
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/ElementCommandsTest.java
app/src/main/java/io/appium/uiautomator2/handler/GetClipboard.java
app/src/main/java/io/appium/uiautomator2/handler/SetClipboard.java
app/src/main/java/io/appium/uiautomator2/utils/ScreenshotHelper.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

Similar to https://github.com/appium/WebDriverAgent/pull/627

fix: Enforce usage of base64 RFC4648 encoder

---

app/src/androidTestE2eTest/java/io/appium/uiautomator2/unittest/test/DeviceCommandsTest.java
app/src/main/java/io/appium/uiautomator2/model/internal/CustomUiDevice.java
app/src/main/java/io/appium/uiautomator2/utils/AXWindowHelpers.java

See issue https://github.com/appium/appium-uiautomator2-server/issues/491

fix: Use Build.VERSION.SDK_INT instead of API_LEVEL_ACTUAL

---

.eslintignore
.github/workflows/functional-test.yml
.github/workflows/publish.js.yml
.github/workflows/unit-test.yml
app/build.gradle
app/src/test/java/io/appium/uiautomator2/utils/XMLHelpersTests.java
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
package.json

Updated AGP to v8 -> this requires Java update to v17 -> this requires unit test update

chore: Update various packages

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

To make match with app's one:
https://github.com/appium/appium-uiautomator2-server/blob/09b4eea3832459ff52e870f54e3e437ce0b3ed65/app/build.gradle#L7-L9

chore: bump gradle env

---

app/src/main/java/io/appium/uiautomator2/utils/actions_scheduler/ScheduledActionsManager.java

Addresses https://discuss.appium.io/t/scheduled-actions-times-parameter/42827

fix: The amount of runs to unschedule an action

---

app/src/main/java/io/appium/uiautomator2/handler/Source.java
app/src/main/java/io/appium/uiautomator2/utils/Attribute.java
app/src/main/java/io/appium/uiautomator2/utils/actions_scheduler/SourceStep.java

Related to https://discuss.appium.io/t/scheduled-actions-xml/42839

chore: Expose standard xml source attributes in the corresponding step

---

app/src/main/java/io/appium/uiautomator2/utils/w3c/ActionsExecutor.java

Related to https://github.com/appium/appium-uiautomator2-driver/issues/923
AI analysis:
> ❌ Why Thread.sleep() is a problem in UIAutomator
> Thread.sleep() often sleeps longer than requested due to thread scheduling.
> UIAutomator runs on a separate process, so app-side timing APIs like Handler or Choreographer are unavailable.
> Sleep inaccuracies accumulate in loops (you may see slow swipes or missed gesture timing).

fix: Prefer LockSupport.parkNanos over Thread.sleep for events injection
